package com.badmintonshop.controller;

import com.badmintonshop.entity.*;
import com.badmintonshop.entity.enums.*;
import com.badmintonshop.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@RestController
@RequestMapping("/api/test/seed")
@RequiredArgsConstructor
public class SeederController {

    private final UserRepository userRepository;
    private final ProductRepository productRepository;
    private final ProductVariantRepository productVariantRepository;
    private final OrderRepository orderRepository;
    private final OrderItemRepository orderItemRepository;
    private final ExchangeRepository exchangeRepository;
    private final WarrantyRepository warrantyRepository;
    private final PasswordEncoder passwordEncoder;

    @GetMapping("/exchange-warranty")
    public String seedExchangeAndWarranty() {
        // 1. Create Test User
        User user = userRepository.findByEmailAndDeletedAtIsNull("test_customer@shop.vn")
                .orElseGet(() -> {
                    User u = new User();
                    u.setEmail("test_customer@shop.vn");
                    u.setPasswordHash(passwordEncoder.encode("123456"));
                    u.setFullName("Test Customer");
                    u.setPhone("0909999999");
                    u.setStatus(UserStatus.ACTIVE);
                    u.setIsEmailVerified(true);
                    return userRepository.save(u);
                });

        // 2. Create Product & Variant
        Product product = productRepository.findAll().stream().findFirst().orElseGet(() -> {
            Product p = new Product();
            p.setName("Vợt Test Seed");
            p.setSlug("vot-test-seed");
            p.setBasePrice(new BigDecimal("1000000"));
            p.setStatus(ProductStatus.ACTIVE);
            return productRepository.save(p);
        });

        ProductVariant variant = productVariantRepository.findAll().stream()
                .filter(v -> v.getProduct().getProductId().equals(product.getProductId()))
                .findFirst().orElseGet(() -> {
                    ProductVariant v = new ProductVariant();
                    v.setProduct(product);
                    v.setSku("TEST-VAR-01");
                    v.setPriceAdjustment(BigDecimal.ZERO);
                    // v.setStockQuantity(100); // Removed as not in entity
                    return productVariantRepository.save(v);
                });

        // 3. Create Order
        Order order = new Order();
        order.setUser(user);
        order.setOrderNumber("ORD-SEED-" + System.currentTimeMillis());
        order.setStatus(OrderStatus.DELIVERED);
        order.setTotalAmount(new BigDecimal("2000000"));
        order.setShippingRecipientName("Test Customer");
        order.setShippingAddress("123 Test Street");
        order.setShippingPhone("0909999999");
        order.setPaymentMethod(PaymentMethod.COD);
        order.setCreatedAt(LocalDateTime.now().minusDays(5));
        order = orderRepository.save(order);

        // 4. Create Order Items
        // Item 1: For Exchange
        OrderItem item1 = new OrderItem();
        item1.setOrder(order);
        item1.setProduct(product);
        item1.setVariant(variant);
        item1.setProductName(product.getName());
        item1.setProductSku(variant.getSku());
        item1.setVariantName(variant.getSku()); // Ensure variant name is set
        item1.setQuantity(1);
        item1.setUnitPrice(product.getBasePrice()); // Use base price
        item1.setSubtotal(product.getBasePrice());
        item1 = orderItemRepository.save(item1);

        // Item 2: For Warranty
        OrderItem item2 = new OrderItem();
        item2.setOrder(order);
        item2.setProduct(product);
        item2.setVariant(variant);
        item2.setProductName(product.getName());
        item2.setProductSku(variant.getSku());
        item2.setVariantName(variant.getSku());
        item2.setQuantity(1);
        item2.setUnitPrice(product.getBasePrice());
        item2.setSubtotal(product.getBasePrice());
        item2 = orderItemRepository.save(item2);

        // 5. Create Exchange Request
        Exchange exchange = new Exchange();
        exchange.setOrder(order);
        exchange.setOrderItem(item1);
        exchange.setOldVariant(variant);
        exchange.setExchangeNumber("EX-SEED-" + System.currentTimeMillis());
        exchange.setReason(ExchangeReason.OTHER);
        exchange.setDescription("Generated by Seeder");
        exchange.setStatus(ExchangeStatus.REQUESTED);
        exchangeRepository.save(exchange);

        // 6. Create Warranty Request
        Warranty warranty = new Warranty();
        warranty.setOrder(order);
        warranty.setOrderItem(item2);
        warranty.setProduct(product);
        warranty.setWarrantyNumber("WAR-SEED-" + System.currentTimeMillis());
        warranty.setIssueType(IssueType.PAINT_PEEL); // Correct enum from IssueType.java
        warranty.setDescription("Generated by Seeder");
        warranty.setStatus(WarrantyStatus.REQUESTED);
        warranty.setPurchaseDate(order.getCreatedAt().toLocalDate());
        warranty.setWarrantyExpiryDate(order.getCreatedAt().toLocalDate().plusMonths(3));
        warrantyRepository.save(warranty);

        return "OK! Created Order " + order.getOrderNumber() + " with 1 Exchange and 1 Warranty request.";
    }
}
